### ISSUE TITLE
Unable start container with external /config directory

### ISSUE THREAD

**Issue by smrowley** [dperson/emby#10]
I tried specifying an external config directory so it could be reused outside the lifecycle of containers. However, when starting the container, it fails with exit code 1 after a few seconds. I tried looking in the container logs, but there was nothing.

I got the container working without specifying an external config directory, but am I correct in assuming that restarting the container would require configuring the server from scratch again?

**Comment by dperson** [comment]
Sorry for the slow reply, I was out of town on vacation.

I'm using the container with an external `/config` directory currently myself. Without it you are correct that it will have to be reconfigured each time.

If you run the command from the `README.md`, do you get any output on your screen?
```
sudo docker run -it --name emby -e TZ=EST5EDT -p 8096:8096 -p 8920:8920 \
            -p 7359:7359/udp -p 1900:1900/udp \
            -v /path/to/directory:/config \
            -v /path/to/media:/media -d dperson/emby
```

**Comment by smrowley** [comment]
I get the container id as output. Then the container terminates after a few seconds.

**Comment by dperson** [comment]
Try running the following:
```
sudo docker run -it --name emby -e TZ=EST5EDT -p 8096:8096 -p 8920:8920 \
            -p 7359:7359/udp -p 1900:1900/udp \
            -v /path/to/directory:/config \
            -v /path/to/media:/media dperson/emby bash
bash -x emby.sh
```
And then send me the output.

**Comment by smrowley** [comment]
I was able to figure out the issue. Your command allowed me to see that SELinux was denying access to the config directory. So I ran the container with -v /path/to/directory:/config:Z

The colon Z tells docker to add a policy to SELinux to allow the container to read/write from the directory.
