### ISSUE TITLE
Don't upgrade docker to 3.2.19.0 EDIT - UPGRADE

### ISSUE THREAD

**Issue by Codgedodger** [dperson/emby#13]
Emby upgrade 3.2.19.0 is making a lot of issues with users and won't load. Please keep docker image on 3.2.17.0 till next update past 3.2.19.0

**Comment by Codgedodger** [comment]
Emby developers have fixed the issue. We are in the clear to upgrade to 3.2.19.0 :)

**Comment by dperson** [comment]
Okay, I've kicked off a new build.
