### ISSUE TITLE
[NO ISSUE] Question

### ISSUE THREAD

**Issue by Codgedodger** [dperson/emby#18]
Question about the docker vs the "official" emby docker. This one shines in comparison in terms of reliability. Why?

I've been playing around with docker and some load balancing via haproxy. I've been using your docker as my one node, then the other IP switch for the server being the "official Linux" docker... I've been running this setup for about a year now and finally asking this question as what tweaks you've done to your image versus the official docker? This image runs beautifully on my dual xeon setup. 

I've be experimenting with this docker in a swarm as haproxy doing the ip handling. Should be pretty interesting when finished.

**Comment by dperson** [comment]
The main reason why I created the image is that there wasn't an official one when started it. It's a bit smaller space wise than the official image with less layers. But, there's not really a killer feature / edge that it has over the official one.

**Comment by gsemet** [comment]
Hello. I compared them both and prefer this one. Easier to setup

**Comment by Codgedodger** [comment]
Hands down this image is better. I don't know what dperson has done, even making things simpler in the coding has made this image stable as a rock. lol 

The "official" docker would suck up close to 30gb of RAM and around 15gb of swap, required to be restarted about once a week. Compared to this image I could have multiple people streaming only using 2-3gb of ram and not need to be restarted unless there is an image update. It's a huge difference in resource consumptions.

**Comment by dperson** [comment]
@Codgedodger @Stibbons well I'm glad to hear that. It makes me quite happy that others use this container as well.
