### ISSUE TITLE
Tag on docker

### ISSUE THREAD

**Issue by gsemet** [dperson/emby#19]
Hello

Can you add a tag when you update the image, because most system don't automatically download `latest`. I usually use version tag to force update.

Thanks !

**Comment by dperson** [comment]
It's building the images with the current packages made available from emby project. For version tags, I know of no way to add them via an API. Docker's system build the image based on the Dockerfile in this repo.

**Comment by gsemet** [comment]
It is pretty easy: simply tag your repository with git and let dockerhub build the same tag and made it available as an image.

**Comment by dperson** [comment]
Tag what exactly though? I'm using the official debian container and auto-built binaries from the Emby project (old ones aren't kept around). If I made a Dockerfile that downloaded a specific version tagged it and setup dockerhub to build/tag it, then it will never build again and it's no better than a hash of the version you like.
