### ISSUE TITLE
Version 3.4.1.0 is now available for download.

### ISSUE THREAD

**Issue by EduardoOliveira** [dperson/emby#20]
Hi,
I am getting the update message for some days now, any idea?

Thanks

**Comment by dperson** [comment]
I'd love to provide newer packages. They don't have them either on the website https://emby.media there the packages are all stuck at 3.2.50. Nor are they on their build system http://download.opensuse.org/repositories/home:/emby/Debian_Next/ where they have 3.3.1 at least.

Tell me where they actually have them, please?

**Comment by EduardoOliveira** [comment]
Not wanting to seem rude in any way, actually this morning I've spent some time searching for a solution and I found an oficial docker image from emby running 3.5.3.0, the parameters are quite similar so I migrated.

Maybe if it is worth it, you could extend their image and add your mojo.

At the moment I am running their image with no problem.

Thank you for your work.
Best regards.

**Comment by dperson** [comment]
Okay, 3.5.0.0 is the latest that's on their github release page, but I've gotten it working now thanks.

**Comment by PhilipWhiteside** [comment]
@dperson is this what you're looking for? https://github.com/MediaBrowser/Emby.Releases/releases the latest stable being 4.1.0.26 from 5 days ago :-) 

It's strange that they removed from the main repo in to this one.
