### ISSUE TITLE
SSL certificates not working

### ISSUE THREAD

**Issue by jseabold** [dperson/emby#22]
Not sure why but I was receiving SSL errors from mono with docker image `f536dcf14d0d`. None of the metadata, etc. was updating. Can reproduce by running

```
csharp -e 'new System.Net.WebClient ().DownloadString ("https://www.nuget.org")'
```

in a running container. I had to go into the container and do `cert-sync /etc/ssl/certs/ca-certificates.crt`. Now things work as expected.

**Comment by dperson** [comment]
Thanks for the report! I hadn't been looking at the logs on my container but it was affected as well.
