### ISSUE TITLE
latin characters in the subtitles

### ISSUE THREAD

**Issue by EduardoOliveira** [dperson/emby#3]
Hello,
first of all awesome image, I've been using it for quite some time.
Two weeks ago I started to notice problems in the latin characters in the subtitles, I've updated the image again this monday but the problem persists.
About 5 or 6 months back I've used an Emby image based on arch linux that had this same problem, then i changed to yours, so I assume its the problem is on the base image and not on emby itself...

Can you please help me out?

**Comment by dperson** [comment]
Do you have an example video that is troublesome? I'll playback a few this evening that I have with subtitles embedded. Just want to make sure I can reproduce the issue you're seeing. Thanks.

**Comment by EduardoOliveira** [comment]
![screen shot 2016-10-19 at 16 03 49](https://cloud.githubusercontent.com/assets/1675917/19524510/e3f87d94-9615-11e6-9556-ee3100849ba9.png)
The ? character was supposed to be an É

**Comment by dperson** [comment]
I've found one possible issue, the localization was being set to just basic `C` (AKA `ascii`). I've set it to `UTF-8` now. Hopefully that helps. Pull down a fresh image and try again, please. Thanks.

**Comment by EduardoOliveira** [comment]
It didn't help, it seems that something in my system (Emby or Sickrage) is setting the encodings of the portuguese subtitles to ISO-8859 and the english ones to UTF8 with BOM.
I don't know what changed in my system, either something changed the encodings or Emby stopped supporting them...

**Comment by dperson** [comment]
Hey, I think that I found the new way to enable UTF-8 in the newer Debian Linux. Please try again if you would. Thanks.
