### ISSUE TITLE
Explain ports used / abuse potential

### ISSUE THREAD

**Issue by bluepuma77** [dperson/emby#4]
Hi,

I just fired up your emby container on an internet server without thinking, not in a local environment. Shortly after I got email from an official government IT agency that I should please check why port 1900/udp is open, that port for SSDP is known for many "DDoS-Reflection" attacks.

```
sudo docker run -it --name emby -e TZ=EST5EDT -p 8096:8096 -p 8920:8920 \
            -p 7359:7359/udp -p 1900:1900/udp -d dperson/emby
```

I think it would be great if you can explain the 4 ports your are opening and maybe even with a hint which ones to use on a local and/or remote  environment.

bluepuma

**Comment by dperson** [comment]
First, the instructions for "opening" the ports, are just the ports that the emby processes listen on. I'm an emby user, and wanted a container for it, when I created this image it was the first on the docker hub. Here is my understanding of what the ports are for:

* 8096 - web server (non-SSL) for local browsing
* 8920 - web server (SSL) for remote browsing
* 1900 UDP - SSDP (Simple Service Discovery Protocol) to aide auto-discovery / ease of setup on the local network
* 7359 UDP - not really sure what they're using it for

Overall: for remote access, I'd really only recommend port 8920 be opened.
