### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by smrowley** [dperson/emby#5]
Hi. First, thanks for creating this docker image. I have the container running on my server, but can't reach the web interface. Just to eliminate some possibilities, I also tried to run the container locally and am still not able to reach it at http://localhost:8096

Here is the container running locally:

CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                                                                            NAMES
b7ce01b24ff0        dperson/emby        "emby.sh -t EST5EDT"   4 minutes ago       Up 3 minutes        0.0.0.0:1900->1900/udp, 0.0.0.0:8096->8096/tcp, 0.0.0.0:7359->7359/udp, 0.0.0.0:8920->8920/tcp   emby

Any suggestions?

**Comment by dperson** [comment]
Well the `docker ps` info shows that it's running, so at least there's that. Next things to check would be if your system is really listening on the ports. You can do so by running: `sudo netstat -lntup | grep docker`

You should see the 4 ports (1900, 7359, 8096, 8920) in the output. To check the container itself, run the following to get the IP: `sudo docker exec -it emby ip addr`

With the IP address run the following (replacing `<IP>` with the actual IP address): `sudo nmap -p1-65535 <IP>`

**Comment by smrowley** [comment]
Everything looks good:

`Starting Nmap 7.40 ( https://nmap.org ) at 2017-01-16 10:32 EST`
`Nmap scan report for 172.17.0.2`
`Host is up (0.0000060s latency).`
`Not shown: 65533 closed ports`
`PORT     STATE SERVICE`
`8096/tcp open  unknown`
`8920/tcp open  unknown`
`MAC Address: 02:42:AC:11:00:02 (Unknown)`

I am able to reach the url with 172.17.0.2. However, I need this to be exposed through the main network interface of the box so I can reach it externally.

**Comment by dperson** [comment]
Can you run the other command on the docker host, please?

`sudo netstat -lntup | grep docker`

Something is obviously not working at some stage.

**Comment by smrowley** [comment]
It is working on my local machine now. The issue is most likely something on my end. Thanks for helping me work through it.

**Comment by dperson** [comment]
Glad it's working for you.
