### ISSUE TITLE
VAAPI 

### ISSUE THREAD

**Issue by vikreddy51** [dperson/emby#6]
I was trying to use the experimental VA API transcoder in Emby.  It looks like the VAAPI drivers are not part of the build.  Is it possible to add?

**Comment by dperson** [comment]
As you can see in the output below, ffmpeg does support VAAPI for encoding. I was under the impression that emby used ffmpeg for all of the transcoding work... if that's wrong I can look at going back to using a non statically linked ffmpeg and have all the libraries separate.

```
$ sudo docker run --rm -it dperson/emby bash
root@444cac711152:/# ffmpeg -encoders 2>/dev/null | grep -i vaa
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... hevc_vaapi           H.265/HEVC (VAAPI) (codec hevc)
 V..... mjpeg_vaapi          MJPEG (VAAPI) (codec mjpeg)
```
