### ISSUE TITLE
Updating Emby Server

### ISSUE THREAD

**Issue by Codgedodger** [dperson/emby#7]
New version of 3.2.6 just came out. Trying to figure out the update command for this docker. What would it be?

**Comment by dperson** [comment]
I kicked off a rebuild of the container, just pull a new version.

**Comment by Codgedodger** [comment]
Emby just updated to 3.2.7

Is there any better way of notifying you? Feel like creating an issue isn't really necessary since it's not really an issue.

**Comment by dperson** [comment]
I had a build trigger that kicked off a new build when there was a new release... which seems to have just stopped working. I've removed it, and recreated it. Hopefully it will work once more.

**Comment by Codgedodger** [comment]
That did it! Thank you sir!
