### ISSUE TITLE
Image Update

### ISSUE THREAD

**Issue by Codgedodger** [dperson/emby#8]
Sorry to bug you again. Image is on 3.2.8 and Emby is on 3.2.10 can we get an update on the image? 👍

**Comment by dperson** [comment]
Sigh, I guess the automatic rebuild link is still broken. I'm subscribed to their blog now in my feed reader, hopefully I'll see the new releases there and kick off the rebuilds manually. Thanks for the heads up, the new container should be in there now.

**Comment by Codgedodger** [comment]
Thanks! :+1:
