### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by Codgedodger** [dperson/emby#9]
Hey mate, 

Sorry to bother again. The docker is for 3.2.10 there has been a couple updates since our last update on the docker. We are on 3.2.12 now. 

Thanks!

**Comment by Codgedodger** [comment]
Now 3.2.13

**Comment by dperson** [comment]
It should be updated once again. I didn't get a notification from the RSS feed either, sigh.

Sorry for the slow update. I was out of town on vacation.
